### ISSUE TITLE
Example Apollo Federation with Apollo Gateway

### ISSUE THREAD

**Issue by g3rd** [cloudflare/workers-graphql-server#12]
I am working on setting up ApolloGateway, but can't seem to figure out how to plug it into the workers-graphql-server.

Has anyone done something similar?

Following: https://github.com/apollographql/federation-demo
Reference: https://www.apollographql.com/docs/apollo-server/federation/introduction/

My long term goal is:

1. ApolloGateway worker on my base domain
2. External GraphQL API
3. Standard GraphQL worker pointing to a REST API
4. Standard GraphQL worker pointing to Neo4j GraphQL

I am currently working on No. 1 connecting to No. 2. I have a somewhat working No. 4 locally, haven't refactored it into a worker yet.

Any advice, examples, or words of encouragement is greatly appreciated!

PS - I'm willing to create a `workers-graphql-gateway-server` template to work alongside this project.

**Comment by signalnerve** [comment]
hey @g3rd! sounds interesting, i've seen gateway mentioned in the docs but haven't played around with it myself. from my basic understanding, you should just be able to point apollo at your GraphQL route - does that not work? if you want to put together a test repo, i'd love to try and help get it working :)

**Comment by g3rd** [comment]
Awesome. Working on it now. 🤞

**Comment by g3rd** [comment]
[Base `workers-graphql-gateway-server`](https://github.com/cementjob/workers-graphql-gateway-server)

**Comment by jopo11** [comment]
Did you have any luck with this? I tried and noticed Apollo gateway was throwing errors as it looks like it was reliant on Node

**Comment by 10thfloor** [comment]
Bump? Does anyone know if this is workable at the moment. 
As far as I can tell, `@apollo/gateway` can't be bundled into a webworker :(

**Comment by nickisyourfan** [comment]
Second the Bump! Would love to know if anyone has had success since?

**Comment by ktheory** [comment]
Related issue on the Apollo side: https://github.com/apollographql/federation/issues/1918

**Comment by damianesteban** [comment]
Is it possible to run Apollo Gateway on AWS (for example) and use cloudflare workers for the federated services?
