### ISSUE TITLE
Local development using wrangler preview -- watch

### ISSUE THREAD

**Issue by ancs21** [cloudflare/workers-graphql-server#16]
Hello @signalnerve ,

I working this repo and worker, need local development to build, testing.
When use `wrangler preview -- watch`, this is don't working.

Thanks.

**Comment by Andrejs1979** [comment]
Same here :(
Webpack is faling

**Comment by Andrejs1979** [comment]
Found the problem. Wrangler generates it's TOML without a reference to the Webpack config. Need to add that line manually. Please amend your docs.

**Comment by ancs21** [comment]
@Andrejs1979 nice. 
Do you share your config file?
Thanks.

**Comment by Andrejs1979** [comment]
Sorry, I was so unhappy with wasted time so I just dropped the whole thing.
But here's the other discussion on this topic: https://github.com/cloudflare/wrangler/issues/296
