### ISSUE TITLE
TypeScript support, build too large

### ISSUE THREAD

**Issue by vladinator1000** [cloudflare/workers-graphql-server#19]
Hi Kris, I've been [working on](https://github.com/vladinator1000/cf-gql) adding TypeScript support but I'm struggling with Wrangler not building correctly.

The only way I got it to build is by mocking modules in the webpack config like this to get the Apollo stuff to work
```js
resolve: {
    extensions: ['.ts', '.tsx', '.js'],
    alias: {
      fs: path.resolve(__dirname, './src/utils/empty.ts'),
      busboy: path.resolve(__dirname, './src/utils/empty.ts'),
    },
  }
```

But this build is 2MiB so it can't get uploaded. Setting it to production mode also didn't help.

I also think that the way we're importing stuff from Apollo is a bit weird, I think Apollo should provide a nice interface that builds and compiles just fine instead of having to wrap the server in a function imported from dist. There's [this issue](https://github.com/apollographql/apollo-server/issues/3838) for example that kinda leaves me scratching my head. 

I have a [simpler TypeScript repo](https://github.com/vladinator1000/ts-cloudflare) that runs and [deploys](https://ts-cloudflare.vlady.workers.dev/) just fine.

If I get this to work, my plan is to convert a medium-sized codebase to Cloudflare workers. You got any pointers on where I can take this?

**Comment by Cerberus** [comment]
Hello @vladinator1000.

As I see your `tsconfig.json`, you have set `"module": "commonjs"` that not supported tree-shaking.

Could you try `"module": "esnext"` instead ?

**Comment by vladinator1000** [comment]
This is how my bundle looks like with  "module": "esnext"` in the TS config.

![image](https://user-images.githubusercontent.com/1226564/82755005-cad1f980-9dc8-11ea-92c1-9cc38b78b05a.png)

**Comment by Cerberus** [comment]
(Seem like this project really bundles a lot of dependencies.)

Anyway, with a quick looking. I have some suggestions.

1. Could you try to change all importing from `/dist` to `/esm` instead (if possible) ? (As I see `graphql-tools` & `apollo-engine-reporting-protobuf`)

As I know the `dist` directory inside `node_modules` always be `commonjs` type. This might help to cut some unused cods off.

2. Update to import directly (`import test from 'lib/test'`) not (`import { test } from 'lib'`)

If you have done already and it's size is still large, I have no idea for now : )

**Comment by Cerberus** [comment]
By the way, I'm the one who start build a project with typescript that scratch from this boilerplate too.

With a few general dependencies, It take lower than 1 MB.

So, hope you found a root cause soon.

**Comment by jayeshmann** [comment]
Can anyone help me with TypeScript implementation of this template?

**Comment by macmillen** [comment]
Hey, can anyone tell me how to set up TypeScript for this library?

**Comment by Shahzayb** [comment]
Here's my template but I'm getting some errors. Can someone help me with this?

https://github.com/Shahzayb/webpack-ts-durable-object-worker

https://webpack-ts-durable-object-worker.shahzaib.workers.dev/___graphql
