### ISSUE TITLE
what is Cloudflare's version of apollo-server ?   how far is the 'apollo-server-cloudflare' different from standard apollo-server ?

### ISSUE THREAD

**Issue by t829702** [cloudflare/workers-graphql-server#26]
I'm trying to figure out from https://www.npmjs.com/package/apollo-server-cloudflare

but it's pointing code Repository as https://github.com/apollographql/apollo-server#readme

What's the reasons Why this demo code can't use a standard upstream apollo-server ?

**Comment by v4iv** [comment]
`apollo-server` maintains a mono-repo, you can find the code for `apollo-server-cloudflare` in the packages folder of the repository

<https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-cloudflare>

**Comment by veryspry** [comment]
+1 to this Q! The lack of documentation around `apollo-server-cloudflare` makes me think that it is an abandoned project and it would be better to roll my own :thinking:
