### ISSUE TITLE
KV caching does not appear to work

### ISSUE THREAD

**Issue by qbunt** [cloudflare/workers-graphql-server#36]
hey @codewithkristian and team! Looks like the KVCache mechanism isn't working as described (or at least I'm not able to use it with the docs provided). I've set the ID properly and I can confirm I'm setting values with that ID via Wrangler, but when I run it in a worker, nothing ever shows up in the KV cache storage.

Is there a specific ttl header I need to set when I'm hitting this server to get the content cached? It's not easy to debug and I'm unclear how I can see what's happening inside `kv-cache.js` when the worker is running. Thanks in advance!

**Comment by devinellis** [comment]
In my case, I wonder if its because I am attempting to cache POST requests to a RESTDataSource?

**Comment by qbunt** [comment]
@devinellis I'm doing a get, but I think I've set all the required variables in the readme, but I also don't know of a way I can debug it easily without pushing it out first

**Comment by qbunt** [comment]
I've got a little more information about this bug. Cache is being read but never written.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/187095/156842336-7a522bad-9bcf-41ff-9f2d-5a8a0f7d6e02.png">

According to [this](https://www.npmjs.com/package/apollo-server-caching) the interface is super simple to implement, and I believe it's connected correctly. Seems possible I need to pass something in the request header to get caching to write correctly or something, but I cannot figure out where

**Comment by qbunt** [comment]
welp, nevermind @devinellis. [Looking through this](https://github.com/apollographql/apollo-server/issues/1562#issuecomment-415829932), apollo will cache based up the RESTDataSource response headers. In our case, not in a position to request that those change, so you can enforce it inside the `resolvers.js` file like this:

```
this.get('/v1/user', null, { cacheOptions: { ttl: 60 } })
```
We're setting these via environment variables, but it may be worth a callout in the docs here, I was completely unaware that the RESTDataSource acted like this.
