### ISSUE TITLE
Migrate to Wrangler 2

### ISSUE THREAD

**Issue by qbunt** [cloudflare/workers-graphql-server#39]
With the release of Wrangler 2, there are a variety of deprecations that should be handled in the wrangler.toml file, as well as a build process change for webpack based workers. Most importantly, Wrangler 2 now supports the ESM module syntax, which will require a number of source code changes. 

We're going to try getting a PR for this together in the upgrade of our own project, but wanted to track this ticket.

**Comment by sebasospina343** [comment]
Any luck with this? I have followed this guide to create a custom build: https://developers.cloudflare.com/workers/wrangler/migration/eject-webpack/#migrate-webpack-projects-from-wrangler-version-1

When I follow the steps, webpack-cli can't find webpack.config file, althought is no longer needed 😪

`[webpack-cli] Failed to load 'C:\Users\user\Desktop\repos\my-app2\webpack.config.js' config`

**Comment by kimyvgy** [comment]
I created a template repository to deploy apollo-server to cloudflare workers during researching about Cloudflare Workers.
It is based on this repository with some changes from me.
- Typescript support
- Wrangler v2
- Esbuild support
- Webpack is removed

Link: https://github.com/kimyvgy/worker-apollo-server

I would like to transfer it to Cloudflare orgnization if I can. Thanks to Cloudflare for the helpful repository.
