### ISSUE TITLE
twitter link goes to suspended account

### ISSUE THREAD

**Issue by jasonkuhrt** [cloudflare/workers-graphql-server#54]
Hey, FYI in your README the twitter link goes to a suspended account 🙃 

![CleanShot 2024-04-10 at 13 30 28@2x](https://github.com/cloudflare/workers-graphql-server/assets/284476/871e0d06-7057-4f4a-a719-63860d33675c)

![CleanShot 2024-04-10 at 13 31 20@2x](https://github.com/cloudflare/workers-graphql-server/assets/284476/59355969-33a0-4029-9f9a-a87e5089b085)

**Comment by Michealflair** [comment]
My suspended twitter account was reinstated permanently by GARIVTECH ON INSTAGRAM 

TELEGRAM 👉t.me/GARIVTECH
