### ISSUE TITLE
Question: Realtime Updates supported

### ISSUE THREAD

**Issue by g3rd** [cloudflare/workers-graphql-server#8]
Does Cloudflare Workers' GraphQL Server allow for subscription / realtime updates?

**Comment by signalnerve** [comment]
Hey @g3rd - we don't currently support it as the Workers platform doesn't have Websockets or anything along those lines. 

You _should_ be able to use the Apollo client's [polling/refetching capabilities](https://www.apollographql.com/docs/react/essentials/queries/#polling-and-refetching), I haven't tested it personally yet, but planning on trying it out at some point in the future. Let me know if you end up trying it!

**Comment by g3rd** [comment]
I'll be giving is a shot soon, and keep you posted!

**Comment by Niko-La** [comment]
@g3rd please keep us updated.  iot needs real time and subscriptions

@signalnerve is there a delay  initially which is typical for serverless functions at the initial bootup? Usually cloud function vendors tell you to run a hack to preserve the function indefinitely.

**Comment by lewisl9029** [comment]
Seems like subscriptions might be possible now with the introduction of durable objects? 
https://blog.cloudflare.com/introducing-workers-durable-objects/

Would love to see this starter extended with subscriptions, or at least some guidelines on best practices.

**Comment by signalnerve** [comment]
> Seems like subscriptions might be possible now with the introduction of durable objects?
> https://blog.cloudflare.com/introducing-workers-durable-objects/
> 
> Would love to see this starter extended with subscriptions, or at least some guidelines on best practices.

Indeed! Since this issue was created Durable Objects have been birthed into existence :) I'm going to take some time this year to look at Durable Objects and if it will allow us to do subscriptions, that would be amazing! No updates at the moment but when we open DO up for public beta, I'd love to have someone else tackle it too if they're interested 👍

**Comment by AlaaZorkane** [comment]
Hey @signalnerve ! Any updates on this? Especially regarding the latest websocket update?
